In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv("genz_social_media_usage_1M.csv")

In [9]:
print("Preview:\n",df.head())
print("\n Total Users: \n", len(df))

Preview:
    age  gender    country  daily_usage_hours primary_platform  \
0   19    Male  Australia           2.658617         Snapchat
1   16  Female        USA           5.685387          Twitter
2   25  Female      India           2.782420           TikTok
3   27    Male      India           3.486598          YouTube
4   23  Female      India           3.748829           TikTok

   num_platforms_used        purpose  avg_session_minutes  night_usage  \
0                   4      Education            29.222443            0
1                   3    Socializing            32.464726            1
2                   2    Socializing            18.170204            1
3                   4      Education            22.493804            1
4                   1  Entertainment            27.358410            1

   mental_health_score addiction_level  screen_time_before_sleep
0             6.705830          Medium                 15.779443
1             6.633111            High                 47.714864
2             6.035397          Medium                 62.524625
3             8.110861          Medium                 31.935102
4             6.658598          Medium                 29.466046

 Total Users:
 1000000

In [10]:
df.columns = df.columns.str.strip().str.lower()
df.dropna(inplace=True)
df.rename(columns={'primary_platform':'platform'},inplace=True)

df

,age,gender,country,daily_usage_hours,platform,num_platforms_used,purpose,avg_session_minutes,night_usage,mental_health_score,addiction_level,screen_time_before_sleep
0,19,Male,Australia,2.658617,Snapchat,4,Education,29.222443,0,6.705830,Medium,15.779443
1,16,Female,USA,5.685387,Twitter,3,Socializing,32.464726,1,6.633111,High,47.714864
2,25,Female,India,2.782420,TikTok,2,Socializing,18.170204,1,6.035397,Medium,62.524625
3,27,Male,India,3.486598,YouTube,4,Education,22.493804,1,8.110861,Medium,31.935102
4,23,Female,India,3.748829,TikTok,1,Entertainment,27.358410,1,6.658598,Medium,29.466046
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,21,Male,India,3.097065,Snapchat,4,Entertainment,21.158532,1,7.230186,Medium,66.317438
999996,14,Male,India,3.663561,Instagram,1,Education,26.312119,1,8.273996,Medium,47.150600
999997,20,Male,India,4.474618,YouTube,2,Socializing,13.623681,0,7.611955,Medium,18.872826
999998,24,Female,Germany,7.829924,YouTube,2,Content Creation,15.789750,1,2.341113,High,62.136012
999999,13,Male,Canada,5.313645,TikTok,1,Socializing,26.397129,1,5.828090,High,34.892929

In [12]:
addiction_map={'Low':1,'Medium':2,'High':3}
df['addiction_score']=df['addiction_level'].map(addiction_map)

df['heavy_user']=np.where(df['daily_usage_hours']> 5, 1, 0)
df

,age,gender,country,daily_usage_hours,platform,num_platforms_used,purpose,avg_session_minutes,night_usage,mental_health_score,addiction_level,screen_time_before_sleep,addiction_score,heavy_user
0,19,Male,Australia,2.658617,Snapchat,4,Education,29.222443,0,6.705830,Medium,15.779443,2,0
1,16,Female,USA,5.685387,Twitter,3,Socializing,32.464726,1,6.633111,High,47.714864,3,1
2,25,Female,India,2.782420,TikTok,2,Socializing,18.170204,1,6.035397,Medium,62.524625,2,0
3,27,Male,India,3.486598,YouTube,4,Education,22.493804,1,8.110861,Medium,31.935102,2,0
4,23,Female,India,3.748829,TikTok,1,Entertainment,27.358410,1,6.658598,Medium,29.466046,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,21,Male,India,3.097065,Snapchat,4,Entertainment,21.158532,1,7.230186,Medium,66.317438,2,0
999996,14,Male,India,3.663561,Instagram,1,Education,26.312119,1,8.273996,Medium,47.150600,2,0
999997,20,Male,India,4.474618,YouTube,2,Socializing,13.623681,0,7.611955,Medium,18.872826,2,0
999998,24,Female,Germany,7.829924,YouTube,2,Content Creation,15.789750,1,2.341113,High,62.136012,3,1
999999,13,Male,Canada,5.313645,TikTok,1,Socializing,26.397129,1,5.828090,High,34.892929,3,1

In [13]:
def age_category(age):
    if age>=10 and age<=15:
        return "Teen"
    elif age>=16 and age<=18:
        return "Late Teen"
    elif age>=19 and age<=22:
        return "Young Adult"
    elif age>=23 and age<=30:
        return "Adult"
def addiction_risk(usage):
    if usage<3:
        return "Low"
    elif usage>=3 and usage<=6:
        return "Medium"
    elif usage>6:
        return "High"

In [14]:
df['age_category']= df['age'].apply(age_category)
df['addiction_risk']=df['daily_usage_hours'].apply(addiction_risk)
df

,age,gender,country,daily_usage_hours,platform,num_platforms_used,purpose,avg_session_minutes,night_usage,mental_health_score,addiction_level,screen_time_before_sleep,addiction_score,heavy_user,age_category,addiction_risk
0,19,Male,Australia,2.658617,Snapchat,4,Education,29.222443,0,6.705830,Medium,15.779443,2,0,Young Adult,Low
1,16,Female,USA,5.685387,Twitter,3,Socializing,32.464726,1,6.633111,High,47.714864,3,1,Late Teen,Medium
2,25,Female,India,2.782420,TikTok,2,Socializing,18.170204,1,6.035397,Medium,62.524625,2,0,Adult,Low
3,27,Male,India,3.486598,YouTube,4,Education,22.493804,1,8.110861,Medium,31.935102,2,0,Adult,Medium
4,23,Female,India,3.748829,TikTok,1,Entertainment,27.358410,1,6.658598,Medium,29.466046,2,0,Adult,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,21,Male,India,3.097065,Snapchat,4,Entertainment,21.158532,1,7.230186,Medium,66.317438,2,0,Young Adult,Medium
999996,14,Male,India,3.663561,Instagram,1,Education,26.312119,1,8.273996,Medium,47.150600,2,0,Teen,Medium
999997,20,Male,India,4.474618,YouTube,2,Socializing,13.623681,0,7.611955,Medium,18.872826,2,0,Young Adult,Medium
999998,24,Female,Germany,7.829924,YouTube,2,Content Creation,15.789750,1,2.341113,High,62.136012,3,1,Adult,High
999999,13,Male,Canada,5.313645,TikTok,1,Socializing,26.397129,1,5.828090,High,34.892929,3,1,Teen,Medium

In [15]:
df.drop_duplicates()
df

,age,gender,country,daily_usage_hours,platform,num_platforms_used,purpose,avg_session_minutes,night_usage,mental_health_score,addiction_level,screen_time_before_sleep,addiction_score,heavy_user,age_category,addiction_risk
0,19,Male,Australia,2.658617,Snapchat,4,Education,29.222443,0,6.705830,Medium,15.779443,2,0,Young Adult,Low
1,16,Female,USA,5.685387,Twitter,3,Socializing,32.464726,1,6.633111,High,47.714864,3,1,Late Teen,Medium
2,25,Female,India,2.782420,TikTok,2,Socializing,18.170204,1,6.035397,Medium,62.524625,2,0,Adult,Low
3,27,Male,India,3.486598,YouTube,4,Education,22.493804,1,8.110861,Medium,31.935102,2,0,Adult,Medium
4,23,Female,India,3.748829,TikTok,1,Entertainment,27.358410,1,6.658598,Medium,29.466046,2,0,Adult,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,21,Male,India,3.097065,Snapchat,4,Entertainment,21.158532,1,7.230186,Medium,66.317438,2,0,Young Adult,Medium
999996,14,Male,India,3.663561,Instagram,1,Education,26.312119,1,8.273996,Medium,47.150600,2,0,Teen,Medium
999997,20,Male,India,4.474618,YouTube,2,Socializing,13.623681,0,7.611955,Medium,18.872826,2,0,Young Adult,Medium
999998,24,Female,Germany,7.829924,YouTube,2,Content Creation,15.789750,1,2.341113,High,62.136012,3,1,Adult,High
999999,13,Male,Canada,5.313645,TikTok,1,Socializing,26.397129,1,5.828090,High,34.892929,3,1,Teen,Medium

In [16]:
df.count()

age                         1000000
gender                      1000000
country                     1000000
daily_usage_hours           1000000
platform                    1000000
num_platforms_used          1000000
purpose                     1000000
avg_session_minutes         1000000
night_usage                 1000000
mental_health_score         1000000
addiction_level             1000000
screen_time_before_sleep    1000000
addiction_score             1000000
heavy_user                  1000000
age_category                1000000
addiction_risk              1000000
dtype: int64

In [17]:
avg_daily_hours = df['daily_usage_hours'].mean()
print(avg_daily_hours)

3.5149983942930905

In [21]:
def get_most_used_platform(platform_col):
    counts = platform_col.value_counts()
    print(counts) 
    return counts.index[0] 

most_used = get_most_used_platform(df['platform'])
print(most_used)

platform
Instagram    299927
YouTube      250292
TikTok       250085
Twitter      100022
Snapchat      99674
Name: count, dtype: int64
Instagram

In [24]:
platform_counts = df['platform'].value_counts()

most_used_platform = platform_counts.idxmax()   # platform name
max_count = platform_counts.max()               # maximum count

print("Platform:", most_used_platform)
print("Count:", max_count)

Platform: Instagram
Count: 299927